package main

import (
	"bytes"
	"io"
	"net/http"
	"net/http/httptest"
	"snippetbox.alsts.net/internal/assert"
	"testing"
)

func TestPing(t *testing.T) {
	// Initialize a new httptest.ResponseRecorder. 
	responseRecorder := httptest.NewRecorder()
	// Initialize a new dummy http.Request.
	request, err := http.NewRequest(http.MethodGet, "/", nil)
	if err != nil {
		t.Fatal(err)
	}
	
	// Call the ping handler function, passing in the // httptest.ResponseRecorder and http.Request. 
	ping(responseRecorder, request)

	// Call the Result() method on the http.ResponseRecorder to get the // http.Response generated by the ping handler.
	result := responseRecorder.Result()
	// Check that the status code written by the ping handler was 200.
	assert.Equal(t, result.StatusCode, http.StatusOK)
	// And we can check that the response body written by the ping handler // equals "OK".
	defer result.Body.Close()
	body, err := io.ReadAll(result.Body)
	if err != nil {
		t.Fatal(err) // stop the test
	}
	bytes.TrimSpace(body)
	assert.Equal(t, string(body), "OK")
}
